# Generated by Django 5.0.2 on 2025-04-29 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('products', '0004_product_manually_unavailable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('message', 'Nuevo mensaje'), ('views', 'Vistas de producto'), ('favorite', 'Añadido a favoritos')], help_text='Tipo de notificación', max_length=20)),
                ('title', models.CharField(help_text='Título de la notificación', max_length=255)),
                ('message', models.TextField(help_text='Cuerpo del mensaje de la notificación')),
                ('is_read', models.BooleanField(default=False, help_text='Indica si la notificación ha sido leída')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(blank=True, help_text='Usuario que origina la notificación (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('related_conversation', models.ForeignKey(blank=True, help_text='Conversación relacionada (para notificaciones de mensajes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='chat.conversation')),
                ('related_product', models.ForeignKey(blank=True, help_text='Producto relacionado con la notificación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='products.product')),
                ('user', models.ForeignKey(help_text='Usuario que recibe la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
