# Generated by Django 5.0.2 on 2025-05-22 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_edited_at_message_is_edited'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_message',
            field=models.ForeignKey(blank=True, help_text='Mensaje relacionado (para notificaciones de likes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='chat.message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('message', 'Nuevo mensaje'), ('views', 'Vistas de producto'), ('favorite', 'Añadido a favoritos'), ('like_message', 'Like en mensaje')], help_text='Tipo de notificación', max_length=20),
        ),
    ]
