# Generated by Django 5.0.2 on 2025-06-02 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rating'),
        ('notifications', '0002_notification_related_message_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_rating',
            field=models.ForeignKey(blank=True, help_text='Calificación relacionada (para notificaciones de nuevas calificaciones)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='accounts.rating'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('message', 'Nuevo mensaje'), ('views', 'Vistas de producto'), ('favorite', 'Añadido a favoritos'), ('like_message', 'Like en mensaje'), ('rating', 'Nueva calificación')], help_text='Tipo de notificación', max_length=20),
        ),
    ]
