# Generated by Django 5.0.2 on 2025-06-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_related_rating_alter_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("message", "Nuevo mensaje"),
                    ("views", "Vistas de producto"),
                    ("favorite", "Añadido a favoritos"),
                    ("like_message", "Like en mensaje"),
                    ("rating", "Nueva calificación"),
                    ("product_rejected", "Producto rechazado"),
                ],
                help_text="Tipo de notificación",
                max_length=20,
            ),
        ),
    ]
