# Generated by Django 5.0.2 on 2025-06-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_alter_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="extra_data",
            field=models.JSONField(
                blank=True,
                help_text="Datos adicionales en formato JSON (motivos de rechazo, etc.)",
                null=True,
            ),
        ),
    ]
