# Generated by Django 5.0.2 on 2025-06-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_emailverificationotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified_seller",
            field=models.BooleanField(default=False),
        ),
    ]
