# Generated by Django 5.0.2 on 2025-06-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_update_uoh_verified_sellers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verification_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
