# Generated by Django 5.0.2 on 2025-06-22 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_user_verification_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="verification_code",
        ),
    ]
