[variables]
NIXPACKS_PYTHON_VERSION = "3.12"

[phases.install]
cmds = ["cd back-end && python -m pip install --upgrade pip && python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["cd back-end && python manage.py collectstatic --noinput"]

[start]
cmd = "cd back-end && python manage.py migrate && daphne -b 0.0.0.0 -p $PORT backend.asgi:application"
