# Generated by Django 5.0.2 on 2025-05-19 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_is_edited_message_liked_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_edited',
            new_name='liked',
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated_at',
        ),
    ]
