# Generated by Django 5.0.2 on 2025-06-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duración en segundos', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_messages/'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Texto'), ('audio', 'Audio')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
