# Generated by Django 5.0.2 on 2025-04-15 01:52

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/', validators=[products.models.validate_image]),
        ),
    ]
