# Generated by Django 5.0.2 on 2025-04-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending', 'En revisión'), ('available', 'Disponible'), ('unavailable', 'No disponible')], default='pending', max_length=20),
        ),
    ]
