# Generated by Django 5.0.2 on 2025-04-29 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manually_unavailable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='review_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
