[providers]
python = ["3.12"]

[variables]
NIXPACKS_PYTHON_VERSION = "3.12"

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "python manage.py migrate && python -m daphne -b 0.0.0.0 -p $PORT backend.asgi:application"
