[build]
builder = "NIXPACKS"

[deploy]
startCommand = "sh -c 'python manage.py migrate && daphne -b 0.0.0.0 -p $PORT backend.asgi:application'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
