# Generated by Django 5.0.2 on 2025-06-23 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_expiringtoken_is_persistent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersession",
            name="user",
        ),
        migrations.DeleteModel(
            name="ExpiringToken",
        ),
        migrations.DeleteModel(
            name="UserSession",
        ),
    ]
